# Automated Sales Data Cleaning & BI Pipeline — Exploratory Walkthrough

Цей ноутбук — покроковий, навчальний варіант пайплайну: він показує *чому* кожен крок очищення потрібен, на прикладах з реальних даних. Продакшн-логіка винесена у пакет `src/` (див. `main.py`), покрита тестами (`pytest`) і перевіряється в CI при кожному пуші — так однакова логіка не дублюється і не розходиться між ноутбуком і продакшн-скриптом.

In [1]:
import pandas as pd

from src import config
from src.loader import load_all_sales_data
from src.cleaning import clean_product_names, clean_prices, clean_quantities, clean_dates, clean_sales_data
from src.reporting import build_monthly_report, build_product_report, build_master_export
from src.exporter import export_report

## Крок 1: Автоматичне виявлення та об'єднання файлів

`load_all_sales_data` шукає всі файли за шаблоном `raw_data/large_sales_month*.csv` через `glob`, перевіряє, що в кожному є всі обов'язкові колонки, і об'єднує їх в один DataFrame. Якщо файлів не знайдено або в якомусь бракує колонки — функція одразу піднімає зрозумілу помилку замість незрозумілого падіння pandas.

In [2]:
raw_df = load_all_sales_data()
print(f"Загальна кількість рядків після об'єднання: {raw_df.shape[0]}")
raw_df.head()

Загальна кількість рядків після об'єднання: 15000

   sale_id              date    product_name    price  quantity
0    10000  2026/01/04 18:00     MacBook Pro     1999       1.0
1    10001  2026/01/20 15:00    macbook air      1100       3.0
2    10002        07/01/2026       iPad Air   599 USD       4.0
3    10003  2026/01/11 07:00        iPad Air      599       5.0
4    10004        2026-01-09        iPad Air   $25.00       1.0

In [3]:
print("--- Загальна інформація про датасет ---")
print(raw_df.info())

print("\n--- Кількість пропущених значень по колонках ---")
print(raw_df.isna().sum())

--- Загальна інформація про датасет ---
<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sale_id       15000 non-null  int64
 1   date          15000 non-null  str
 2   product_name  14518 non-null  str
 3   price         14579 non-null  str
 4   quantity      14723 non-null  float64
dtypes: float64(1), int64(1), str(3)
memory usage: 586.1 KB
None

--- Кількість пропущених значень по колонках ---
sale_id           0
date              0
product_name    482
price           421
quantity        277
dtype: int64

## Крок 2: Очищення назв товарів, цін і кількості

- **Назви товарів** — прибираємо пробіли й зводимо регістр до Title Case, з винятками для назв, які Title Case ламає (`iPhone`, `MacBook`, `AirPods`, `Wi-Fi`). Це надійніше за жорсткий словник відповідностей: нові регістрові варіації того самого товару об'єднаються автоматично.
- **Ціни** — прибираємо `$`, коми, пробіли й слово `USD`, конвертуємо в число. Пропуски заповнюємо **медіаною ціни того ж товару** (а не глобальною медіаною), щоб не спотворити дешеві/дорогі категорії.
- **Кількість** — пропуски заповнюємо базовим припущенням `1` і приводимо до `int`.

In [4]:
product_name_cleaned = clean_product_names(raw_df['product_name'])
price_cleaned = clean_prices(raw_df['price'], product_name_cleaned)
quantity_cleaned = clean_quantities(raw_df['quantity'])

print("--- Унікальні назви товарів після очищення ---")
print(sorted(product_name_cleaned.unique()))

print("\n--- Приклад очищення цін ---")
pd.DataFrame({
    'product_name': raw_df['product_name'],
    'price_raw': raw_df['price'],
    'price_cleaned': price_cleaned,
}).head(10)

--- Унікальні назви товарів після очищення ---
['AirPods Pro', 'MacBook Air', 'MacBook Pro', 'Powerbank 65W', 'Unknown Product', 'Wi-Fi Adapter', 'iPad Air', 'iPhone 15 Pro']

--- Приклад очищення цін ---

      product_name price_raw  price_cleaned
0      MacBook Pro      1999        1999.00
1     macbook air       1100        1100.00
2        iPad Air    599 USD         599.00
3         iPad Air       599         599.00
4         iPad Air    $25.00          25.00
5              NaN       65$          65.00
6    Wi-Fi Adapter  1999 USD        1999.00
7   iPhone 15 Pro    999.99$         999.99
8      MacBook Air       25$          25.00
9    Wi-Fi Adapter        65          65.00

## Крок 3: Розбір дат у змішаних форматах

Джерельні файли містять дати одразу в чотирьох форматах (`YYYY-MM-DD`, `YYYY/MM/DD`, `DD/MM/YYYY`, `MM-DD-YYYY`). Наївний автоматичний розбір (`pd.to_datetime(..., format='mixed')`) для неоднозначних дат на кшталт `10/02/2026` вгадує `MM/DD/YYYY` (10 жовтня) — хоча реальні дані лежать лише в Q1 2026, тобто це мало б бути 10 лютого. Тому `clean_dates` пробує формати в явному пріоритетному порядку (`config.DATE_FORMATS`) і застосовує наступний формат тільки до ще нерозпізнаних значень.

In [5]:
date_cleaned = clean_dates(raw_df['date'])

unparsed = date_cleaned.isna().sum()
print(f"Дат, які не вдалося розпізнати: {unparsed}")

pd.DataFrame({'date_raw': raw_df['date'], 'date_cleaned': date_cleaned}).head(10)

Дат, які не вдалося розпізнати: 0

           date_raw date_cleaned
0  2026/01/04 18:00   2026-01-04
1  2026/01/20 15:00   2026-01-20
2        07/01/2026   2026-01-07
3  2026/01/11 07:00   2026-01-11
4        2026-01-09   2026-01-09
5        11/01/2026   2026-01-11
6        05/01/2026   2026-01-05
7  2026/01/16 00:00   2026-01-16
8        2026-01-09   2026-01-09
9        2026-01-21   2026-01-21

## Крок 4: Фінансові метрики та BI-звіти

`clean_sales_data` застосовує всі кроки очищення разом і рахує `total_revenue` (`price_cleaned * quantity_cleaned`). Далі агрегуємо один раз — і саме ці цифри йдуть і в друк, і у фінальний Excel, без розбіжностей між ними.

In [6]:
clean_df = clean_sales_data(raw_df)

monthly_report = build_monthly_report(clean_df)
product_report = build_product_report(clean_df)

print("=== MONTHLY BUSINESS PERFORMANCE REPORT ===")
print(monthly_report.to_string(index=False))

print("\n=== TOP PRODUCTS BY REVENUE REPORT ===")
print(product_report.to_string(index=False))

=== MONTHLY BUSINESS PERFORMANCE REPORT ===
year_month  total_sales_volume  total_revenue_usd  average_ticket
   2026-01               15431        10760560.37     2084.975852
   2026-02               14384        10393922.87     2147.948516
   2026-03               14846        10787251.28     2157.450256

=== TOP PRODUCTS BY REVENUE REPORT ===
product_name_cleaned  units_sold  revenue_generated_usd
       iPhone 15 Pro        8903             6504176.78
         MacBook Air        8599             6154171.83
            iPad Air        8542             6103376.95
       Powerbank 65W        4270             3092961.79
         MacBook Pro        4405             3055136.74
       Wi-Fi Adapter        4225             3010527.33
         AirPods Pro        4274             2992043.86
     Unknown Product        1443             1029339.24

## Крок 5: Експорт у стилізований багатоаркушевий Excel-файл

`export_report` записує очищений master-датасет і обидва BI-звіти в один `.xlsx` з корпоративним стилем (заморожені заголовки, фірмові кольори, валютне форматування, автоширина колонок).

In [7]:
master_export = build_master_export(clean_df)
output_path = export_report(master_export, monthly_report, product_report)
print(f"[SUCCESS] Файл '{output_path}' збережено.")

[SUCCESS] Файл '/home/claude/build/final_sales_analytics_report.xlsx' збережено.